name = "jasmine"
main = "src/index.ts"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "mtc_tokens"
id = "5f3e4458f1ff46808d668926cd6b352f"
preview_id = "044795d052f44a8d96b3e27b1c89357f"

 [[queues.producers]]
 binding = "QUEUE"
 queue = "mill"

